summary: Get a user's settings
operationId: getUserSettings
tags:
  - user
description: >-
  Retrieves a user’s settings.
  Will return a 200 OK with a JSON object representing the user’s personal settings (if any) as body.
parameters:
  - $ref: ../../../components/parameters/username.yaml
responses:
  "200":
    description: >-
      User settings
    content:
      application/json:
        schema:
          type: object
          additionalProperties: true
  "403":
    description: >-
      No admin rights and not logged in as the user
  "404":
    description: >-
      Unknown user
