openapi: 3.0.2
info:
  title: OctoPrint
  version: '1.0'
servers:
  - url: 'http://192.168.178.66:5000/api'
paths:
  /login:
    $ref: paths/login.yaml
  /logout:
    $ref: paths/logout.yaml
  /currentuser:
    $ref: paths/currentuser.yaml
  /version:
    $ref: paths/version.yaml
  /connection:
    $ref: paths/connection.yaml
  /printer:
    $ref: paths/printer.yaml
  /printer/tool:
    $ref: paths/printer@tool.yaml
