openapi: 3.0.2
info:
  license:
    name: Creative Commons
    url: https://creativecommons.org/licenses/by/3.0
  title: OctoPrint
  description: API client for the OctoPrint 3D printer control server
  version: "1.0"
servers:
  - url: "http://192.168.178.66:5000/api"
paths:
  /login:
    $ref: paths/login.yaml
  /logout:
    $ref: paths/logout.yaml
  /currentuser:
    $ref: paths/currentuser.yaml
  /version:
    $ref: paths/version.yaml
  /connection:
    $ref: paths/connection.yaml

  /files/{location}:
    get:
      $ref: paths/files/{location}/get.yaml
    post:
      $ref: ./paths/files/{location}/post.yaml
  /files/{location}/{path}:
    get:
      $ref: ./paths/files/{location}/{path}-get.yaml
    delete:
      $ref: ./paths/files/{location}/{path}-delete.yaml
  /files:
    get:
      $ref: paths/files/get.yaml
  /job:
    get:
      $ref: paths/job/get.yaml
    post:
      $ref: paths/job/post.yaml
  /printer:
    get:
      $ref: paths/printer/get.yaml
  /printer/tool:
    get:
      $ref: paths/printer/tool-get.yaml
    post:
      $ref: paths/printer/tool-post.yaml
  /printer/bed:
    get:
      $ref: paths/printer/bed-get.yaml
    post:
      $ref: paths/printer/bed-post.yaml
  /printer/chamber:
    get:
      $ref: paths/printer/chamber-get.yaml
    post:
      $ref: paths/printer/chamber-post.yaml
  /printer/sd:
    get:
      $ref: paths/printer/sd-get.yaml
    post:
      $ref: paths/printer/sd-post.yaml
  /printer/command:
    post:
      $ref: paths/printer/command-post.yaml
