openapi: 3.0.2
info:
  license:
    name: Creative Commons
    url: https://creativecommons.org/licenses/by/3.0
  title: OctoPrint
  description: API client for the OctoPrint 3D printer control server
  version: "1.0"
servers:
  - url: "http://192.168.178.66:5000/api"
paths:
  /login:
    $ref: paths/login.yaml
  /logout:
    $ref: paths/logout.yaml
  /currentuser:
    $ref: paths/currentuser.yaml
  /version:
    $ref: paths/version.yaml
  /connection:
    $ref: paths/connection.yaml

  /files/{location}:
    get:
      $ref: paths/files/{location}/get.yaml
    post:
      $ref: ./paths/files/{location}/post.yaml
  /files/{location}/{path}:
    get:
      $ref: ./paths/files/{location}/{path}-get.yaml
    delete:
      $ref: ./paths/files/{location}/{path}-delete.yaml
  /files:
    get:
      $ref: paths/files/get.yaml
  /job:
    get:
      $ref: paths/job/get.yaml
    post:
      $ref: paths/job/post.yaml
  /printer:
    get:
      $ref: paths/printer/get.yaml
  /printer/tool:
    get:
      $ref: paths/printer/tool-get.yaml
    post:
      $ref: paths/printer/tool-post.yaml
  /printer/bed:
    get:
      $ref: paths/printer/bed-get.yaml
    post:
      $ref: paths/printer/bed-post.yaml
  /printer/chamber:
    get:
      $ref: paths/printer/chamber-get.yaml
    post:
      $ref: paths/printer/chamber-post.yaml
  /printer/sd:
    get:
      $ref: paths/printer/sd-get.yaml
    post:
      $ref: paths/printer/sd-post.yaml
  /printer/command/custom:
    get:
      $ref: paths/printer/command/custom-get.yaml
  /printer/command:
    post:
      $ref: paths/printer/command/post.yaml
  /printerprofiles:
    get:
      $ref: paths/printerprofiles/get.yaml
    post:
      $ref: paths/printerprofiles/post.yaml
  /printerprofiles/{identifier}:
    get:
      $ref: paths/printerprofiles/{identifier}-get.yaml
    post:
      $ref: paths/printerprofiles/{identifier}-post.yaml
    delete:
      $ref: paths/printerprofiles/{identifier}-delete.yaml
  /system/commands:
    get:
      $ref: paths/system/commands/get.yaml
  /system/commands/{source}:
    get:
      $ref: paths/system/commands/{source}-get.yaml
  /system/commands/{source}/{action}:
    post:
      $ref: paths/system/commands/{source}-{action}-post.yaml
  /access/permissions:
    get:
      $ref: paths/access/permissions-get.yaml
  /access/groups:
    get:
      $ref: paths/access/groups/get.yaml
    post:
      $ref: paths/access/groups/post.yaml
  /access/groups/{key}:
    get:
      $ref: paths/access/groups/{key}-get.yaml
    put:
      $ref: paths/access/groups/{key}-put.yaml
    delete:
      $ref: paths/access/groups/{key}-delete.yaml
  /access/users:
    get:
      $ref: paths/access/users/get.yaml
    post:
      $ref: paths/access/users/post.yaml
  /access/users/{username}:
    get:
      $ref: paths/access/users/{username}-get.yaml
    put:
      $ref: paths/access/users/{username}-put.yaml
    delete:
      $ref: paths/access/users/{username}-delete.yaml
  /access/users/{username}/password:
    put:
      $ref: paths/access/users/{username}-password-put.yaml
