openapi: 3.0.2
info:
  license:
    name: Creative Commons
    url: https://creativecommons.org/licenses/by/3.0
  title: OctoPrint
  description: API client for the OctoPrint 3D printer control server
  version: "1.0"
servers:
  - url: "http://192.168.178.66:5000/api"
paths:
  /login:
    $ref: paths/login.yaml
  /logout:
    $ref: paths/logout.yaml
  /currentuser:
    $ref: paths/currentuser.yaml
  /version:
    $ref: paths/version.yaml
  /connection:
    $ref: paths/connection.yaml
  /printer:
    $ref: paths/printer.yaml
  /files/local:
    $ref: paths/files/local.yaml
  /files/sdcard:
    $ref: paths/files/sdcard.yaml
  /files:
    $ref: paths/files/get.yaml
  /printer/tool:
    $ref: paths/printer@tool.yaml
