name: Build Docs

on:
  release:
    types: [published]
  # For this workflow, we're using the workflow_dispatch event which is triggered when the user clicks Run workflow in the GitHub Actions UI
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test OpenAPI specification
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm ci
      - run: npm run test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm ci
      - run: npm run test
      - run: npm run build
      - run: npm run build-docs
      - name: Deploy Docs 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
  dispatch:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Read package.json
        uses: dutscher/read-package-json-endpoint-actions@v1.33.7
        id: package-json-endpoint
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: gosticks/octoprint-ts-client
          event-type: api-updated
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "changelog: "Test changelog", "tag": "${{ steps.package-json-endpoint.outputs.version }}"}'
